#!/bin/bash
set -e

# CRIAR USUÁRIOS
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$SONARQUBE_DB_USER" WITH PASSWORD '$SONARQUBE_DB_PASSWORD' SUPERUSER CREATEDB CREATEROLE;
    CREATE USER "$GITEA_DATABASE_USER" WITH PASSWORD '$GITEA_DB_PASSWORD' SUPERUSER CREATEDB CREATEROLE;
    CREATE USER "$DRONE_DATABASE_USER" WITH PASSWORD '$DRONE_DB_PASSWORD' SUPERUSER CREATEDB CREATEROLE;
EOSQL

# CRIAR BANCOS E PERMISSÕES
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE sonarqube ENCODING 'UTF8' OWNER "$SONARQUBE_DB_USER";
    CREATE DATABASE gitea ENCODING 'UTF8' OWNER "$GITEA_DATABASE_USER";
    CREATE DATABASE drone ENCODING 'UTF8' OWNER "$DRONE_DATABASE_USER";
EOSQL

# PERMISSÕES SONARQUBE
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "sonarqube" <<-EOSQL
    GRANT ALL ON SCHEMA public TO "$SONARQUBE_DB_USER";
EOSQL

# PERMISSÕES GITEA
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "gitea" <<-EOSQL
    GRANT ALL ON SCHEMA public TO "$GITEA_DATABASE_USER";
EOSQL

# PERMISSÕES DRONE
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "drone" <<-EOSQL
    GRANT ALL ON SCHEMA public TO "$DRONE_DATABASE_USER";
EOSQL