global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'gitea'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gitea:3000'] # Se o Gitea expuser métricas

  - job_name: 'drone'
    static_configs:
      - targets: ['drone-server:80']

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']